"""
Neo4j Transactions Base Model aligned abbreviations mapping.

This module contains comprehensive abbreviation mappings specifically aligned 
with the Neo4j Transactions Base Model terminology to enable high-quality 
schema comparison and compliance checking.
"""

# Neo4j Transactions Base Model aligned abbreviations mapping
NEO4J_ABBREVIATIONS = {
    # Core Neo4j Customer entity abbreviations
    'cust': 'customer',
    'client': 'customer',
    'custnum': 'customerId',
    'clientid': 'customerId',
    'custid': 'customerId',
    'customernum': 'customerId',
    'customerno': 'customerId',
    'fname': 'firstName',
    'firstname': 'firstName',
    'lname': 'lastName',
    'lastname': 'lastName',
    'mname': 'middleName',
    'middlename': 'middleName',
    'dob': 'dateOfBirth',
    'birthdate': 'dateOfBirth',
    'birthdt': 'dateOfBirth',
    'birthplace': 'placeOfBirth',
    'birthcountry': 'countryOfBirth',
    'birthctry': 'countryOfBirth',
    
    # Neo4j Account entity abbreviations
    'acct': 'account',
    'acc': 'account',
    'acctnum': 'accountNumber',
    'accountnum': 'accountNumber',
    'accountno': 'accountNumber',
    'acctno': 'accountNumber',
    'accnum': 'accountNumber',
    'accttype': 'accountType',
    'accounttype': 'accountType',
    'acctype': 'accountType',
    'opendt': 'openDate',
    'opendate': 'openDate',
    'closedt': 'closedDate',
    'closeddate': 'closedDate',
    'suspenddt': 'suspendedDate',
    'suspendeddate': 'suspendedDate',
    
    # Neo4j Transaction entity abbreviations
    'txn': 'transaction',
    'tx': 'transaction',
    'trx': 'transaction',
    'trans': 'transaction',
    'txnid': 'transactionId',
    'transactionid': 'transactionId',
    'txid': 'transactionId',
    'transid': 'transactionId',
    'amt': 'amount',
    'txnamt': 'amount',
    'transamt': 'amount',
    'transactionamt': 'amount',
    'curr': 'currency',
    'currency': 'currency',
    'currencycd': 'currency',
    'currcd': 'currency',
    'msg': 'message',
    'txnmsg': 'message',
    'transmsg': 'message',
    'transactionmsg': 'message',
    'txndt': 'date',
    'transactiondt': 'date',
    'txdate': 'date',
    'transactiondate': 'date',
    'txn_dt': 'date',
    'transaction_dt': 'date',
    
    # Neo4j Movement entity abbreviations  
    'mov': 'movement',
    'movid': 'movementId',
    'movementid': 'movementId',
    'movdesc': 'description',
    'movedesc': 'description',
    'movementdesc': 'description',
    'movstatus': 'status',
    'movementstatus': 'status',
    'seqnum': 'sequenceNumber',
    'sequencenum': 'sequenceNumber',
    'sequenceno': 'sequenceNumber',
    'seqno': 'sequenceNumber',
    
    # Common field abbreviations
    'num': 'number',
    'nbr': 'number',
    'no': 'number',
    'id': 'identifier',
    'ident': 'identifier',
    'desc': 'description',
    'bal': 'balance',
    'dt': 'date',
    'tm': 'time',
    'ts': 'timestamp',
    'cd': 'code',
    'typ': 'type',
    'cat': 'category',
    'grp': 'group',
    'ref': 'reference',
    'seq': 'sequence',
    'cnt': 'count',
    'qty': 'quantity',
    'pct': 'percent',
    'ind': 'indicator',
    'flg': 'flag',
    'sts': 'status',
    'stat': 'status',
    'val': 'value',
    'max': 'maximum',
    'min': 'minimum',
    'avg': 'average',
    'std': 'standard',
    'curr': 'current',
    'prev': 'previous',
    'orig': 'original',
    'src': 'source',
    'tgt': 'target',
    'dest': 'destination',
    
    # Address and contact abbreviations (Neo4j model extensions)
    'addr': 'address',
    'address': 'address',
    'st': 'street',
    'str': 'street',
    'ave': 'avenue',
    'blvd': 'boulevard',
    'rd': 'road',
    'ln': 'lane',
    'zip': 'postalCode',
    'postal': 'postalCode',
    'postalcd': 'postalCode',
    'email': 'email',
    'emailaddr': 'email',
    'phone': 'phone',
    'phonenum': 'phone',
    'tel': 'phone',
    'mobile': 'phone',
    'cell': 'phone',
    
    # Financial and regulatory abbreviations
    'kyc': 'knowYourCustomer',
    'aml': 'antiMoneyLaundering',
    'cdd': 'customerDueDiligence',
    'edd': 'enhancedDueDiligence',
    'pep': 'politicallyExposedPerson',
    'sanction': 'sanctions',
    'watchlist': 'watchList',
    'riskrating': 'riskRating',
    'riskscore': 'riskScore',
    
    # Document and verification abbreviations
    'doc': 'document',
    'passport': 'passport',
    'license': 'drivingLicense',
    'drivinglicense': 'drivingLicense',
    'ssn': 'socialSecurityNumber',
    'sin': 'socialInsuranceNumber',
    'nin': 'nationalIdentificationNumber',
    'vin': 'vehicleIdentificationNumber',
    'exp': 'expiration',
    'expiry': 'expiration',
    'eff': 'effective',
    'effective': 'effective',
    'verify': 'verification',
    'verification': 'verification',
    'verifydt': 'verificationDate',
    'verificationdt': 'verificationDate',
    'verifymthd': 'verificationMethod',
    'verificationmthd': 'verificationMethod',
    'verifysts': 'verificationStatus',
    'verificationsts': 'verificationStatus',
    
    # Technology and system abbreviations
    'ip': 'ipAddress',
    'ipaddr': 'ipAddress',
    'device': 'device',
    'deviceid': 'deviceId',
    'session': 'session',
    'sessionid': 'sessionId',
    'location': 'location',
    'geo': 'geographic',
    'gps': 'geographicPosition',
    'lat': 'latitude',
    'lng': 'longitude',
    'long': 'longitude',
    
    # Banking specific abbreviations
    'iban': 'internationalBankAccountNumber',
    'swift': 'swiftCode',
    'bic': 'bankIdentifierCode',
    'routing': 'routingNumber',
    'sort': 'sortCode',
    'bsb': 'bankStateBranch',
    'branch': 'branch',
    'branchcd': 'branchCode',
    'branchcode': 'branchCode',
    'clearing': 'clearingCode',
    'clearingcd': 'clearingCode'
}